// <auto-generated />
namespace Midterm.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class DataLengthChanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DataLengthChanged));
        
        string IMigrationMetadata.Id
        {
            get { return "202012080626544_DataLengthChanged"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
